# No escape delay
set -sg escape-time 0

#window options
# Set vim mode keybindings
set-window-option -g mode-keys vi
set-window-option -g wrap-search off

# force tmux to source bashrc
set-option -g default-command "/bin/bash"

# Tmux stuff
bind BSpace source-file ~/.tmux.conf \; display-message "Config reloaded.."
bind ? list-keys -N

# Better copy mode
# copy to clipboard
bind -n C-M-v copy-mode
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi p paste-buffer
unbind '['
unbind ']'

######
# Panes and windows
# split panes using | and -
bind | if -F '#{@default_path}' 'split-window -h -c "#{@default_path}"' 'split-window -h'
bind - if -F '#{@default_path}' 'split-window -v -c "#{@default_path}"' 'split-window -v'
unbind '"'
unbind %
unbind 'l'

# Vim switch windows
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
| grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

is_fzf="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?fzf$'"

bind -n C-h run "($is_vim && tmux send-keys C-h) || \
                          if [ $(tmux display-message -p '#{pane_at_left}') -ne 1 ]; then tmux select-pane -L; fi"

bind -n C-l run  "($is_vim && tmux send-keys C-l) || \
                          if [ $(tmux display-message -p '#{pane_at_right}') -ne 1 ]; then tmux select-pane -R; fi"

bind -n C-j run "($is_vim && tmux send-keys C-j)  || \
                         ($is_fzf && tmux send-keys C-j) || \
                         if [ $(tmux display-message -p '#{pane_at_bottom}') -ne 1 ]; then tmux select-pane -D; fi"

bind -n C-k run "($is_vim && tmux send-keys C-k) || \
                          ($is_fzf && tmux send-keys C-k)  || \
                          if [ $(tmux display-message -p '#{pane_at_top}') -ne 1 ]; then tmux select-pane -U; fi"


bind C-h if -bF '#{pane_at_left}' '' 'select-pane -L'
bind C-l if -bF '#{pane_at_right}' '' 'select-pane -R'
bind C-k if -bF '#{pane_at_top}' '' 'select-pane -U'
bind C-j if -bF '#{pane_at_bottom}' '' 'select-pane -D'

# Alt+number to switch windows
bind -n M-1 select-window -t 0
bind -n M-2 select-window -t 1
bind -n M-3 select-window -t 2
bind -n M-4 select-window -t 3
bind -n M-5 select-window -t 4
bind -n M-6 select-window -t 5
bind -n M-7 select-window -t 6
bind -n M-8 select-window -t 7
bind -n M-9 select-window -t 8
bind -n M-0 select-window -t 9

# mouse mode
set -g mouse on

# Moving panes
bind p previous-window

# Reorder windows
bind < swap-window -t -1 \; select-window -t -1
bind > swap-window -t +1 \; select-window -t +1

bind -n C-M-l resize-pane -R 10 \; run "($is_vim && tmux send-keys C-w \"=\") \
|| true"
bind -n C-M-h resize-pane -L 10 \; run "($is_vim && tmux send-keys C-w \"=\") \
|| true"
bind -n C-M-j resize-pane -D 10 \; run "($is_vim && tmux send-keys C-w \"=\") \
|| true"
bind -n C-M-k resize-pane -U 10 \; run "($is_vim && tmux send-keys C-w \"=\") \
|| true"

# Alt+hjkl to swap/move panes
bind -n M-k swap-pane -t '{up-of}'
bind -n M-j swap-pane -t '{down-of}'
bind -n M-h swap-pane -t '{left-of}'
bind -n M-l swap-pane -t '{right-of}'

# Set window default directory to current pane's directory
bind C run 'tmux set-option -w @default_path "#{pane_current_path}" && tmux display-message "Window dir: #{pane_current_path}"'

# ctrl+R to rename panes
bind-key R command-prompt -p "New pane name:" "select-pane -T '%%'"

# # Monitor for 5 seconds of silence, then trigger a notification
set -g monitor-silence 2
set -g visual-silence off

# Allow escape sequences to pass through to the terminal
set -g allow-passthrough on
