ctags_url='https://github.com/universal-ctags/ctags.git'
rust_url='https://sh.rustup.rs'
ripgrep_url='https://github.com/BurntSushi/ripgrep'
#tmux_url='https://github.com/tmux/tmux/archive/3.1b.tar.gz'
tmux_url='https://github.com/tmux/tmux.git'
fzf_url='https://github.com/junegunn/fzf.git'
# Get the precompiled nvim
#nvim_url='https://github.com/neovim/neovim/archive/nightly.tar.gz'
nvim_url='https://github.com/neovim/neovim.git'

# build dependencies
cmake_url='https://github.com/Kitware/CMake/archive/refs/tags/v4.1.0-rc4.tar.gz'
libevent_url='https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz'
libevent_asc='https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz.asc'
ncurses_url='https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz'
ncurses_asc='https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.4.tar.gz.sig'
autoconf_url='https://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz'
autoconf_asc='https://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz.sig'
automake_url='https://ftp.gnu.org/gnu/automake/automake-1.16.tar.gz'
automake_asc='https://ftp.gnu.org/gnu/automake/automake-1.16.tar.gz'
pkgconfig_url='http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz'
pkgconfig_asc='https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz.asc'
bison_url='https://ftp.gnu.org/gnu/bison/bison-3.7.2.tar.gz'
bison_asc='https://ftp.gnu.org/gnu/bison/bison-3.7.2.tar.gz.sig'
m4_url='ftp://ftp.gnu.org:21/gnu/m4/m4-1.4.18.tar.gz'
libtool_url='https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz'
gettext_url='https://ftp.gnu.org/pub/gnu/gettext/gettext-0.21.tar.gz'
unzip_url='https://github.com/LuaDist/unzip'
alacritty_url='https://github.com/alacritty/alacritty/archive/refs/tags/v0.11.0.tar.gz'
freetype_url='https://download.savannah.gnu.org/releases/freetype/freetype-2.11.1.tar.gz'
fontconfig_url='https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.14.1.tar.gz'
gperf_url='http://ftp.gnu.org/pub/gnu/gperf/gperf-3.1.tar.gz'
expat_url='https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.gz'
